config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  resources :posts do
    resources :comments
  end
  root "posts#index"

  get ":user_name", to: "profiles#show", as: :profile
  get ":user_name/edit", to: "profiles#edit", as: :edit_profile
  patch ":user_name/edit", to: "profiles#update", as: :update_profile

  get "notifications/:id/link_through", to: "notifications#link_through", as: :link_through
  get "notifications", to: "notifications#index"
  post ":user_name/follow_user", to: "relationships#follow_user", as: :follow_user
  post ":user_name/unfollow_user", to: "relationships#unfollow_user", as: :unfollow_user
  get "browse", to: "posts#browse", as: :browse_posts
  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user
  before_action :owned_profile, only: [ :edit, :update ]
  before_action :authenticate_user!

  def show
  end

  def edit
  end

  def update
    if @user.update(profile_params)
      flash[:success] = "Your profile has been updated."
      redirect_to profile_path(@user.user_name)
    else
      flash[:error] = @user.errors.full_messages
      render :edit
    end
  end

  private
    def profile_params
      params.require(:user).permit(:bio)
    end

    def owned_profile
      unless current_user == @user
        flash[:alert] = "That profile doesn't belong to you!"
        redirect_to root_path
      end
    end

    def set_user
      @user = User.find_by(user_name: params[:user_name])
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def current_user_is_following(current_user_id, followed_user_id)
    relationship = Follow.find_by(follower_id: current_user_id, following_id: followed_user_id)
    true if relationship
  end
end

app/views/profiles/edit.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="post-body">
      <div class="image-wrap">
        <%= form_for @user, url: {action: "update"}, html: {multipart: true } do |f| %>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group text-center">
                <h4>Update your bio:</h4>
                <%= f.text_area :bio, label: false, rows: 4 %>
              </div>
            </div>
          </div>

          <div class="form-group text-center">
            <%= f.submit "Update Profile", class: "btn btn-success" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
          

app/views/profiles/follow_user.js.erb
$('#follow-button').attr('class', 'btn unfollow-button').text('Following').attr('href', "/<%= @user.user_name %>/unfollow_user").attr('id', 'unfollow-button');

app/views/profiles/show.html.erb
<div class="posts-wrapper">
  <div class="row profile-header">
    <div class="col-md-6">
      <div class="img-circle">
      </div>
    </div>

    <div class="col-md-6">
      <div class="user-name-and-follow">
        <h3 class="profile-user-name">
          <%= @user.user_name %>
        </h3>
        <span>
          <% if current_user && @user == current_user %>
            <%= link_to 'Edit Profile', edit_profile_path(@user.user_name), class: "btn edit-button" %>
          <% else %>
            <% if current_user && current_user_is_following(current_user.id, @user.id) %>
              <%= link_to 'Following', unfollow_user_path, remote: true, class: 'btn unfollow-button', id: 'unfollow-button', method: :post %>
            <% elsif current_user %>
              <%= link_to 'Follow', follow_user_path, remote: true, class: 'btn unfollow-button', id: 'unfollow-button', method: :post %>
            <% end %>
          <% end %>
        </span>
      </div>
      <p class="profile-bio">
        <%= @user.bio %>
      </p>
      <div class="user-statistics">
        <p>
          <%= pluralize @user.posts.count, 'post' %>
        </p>
      </div>
    </div>
  </div>
</div>

<% @posts.each do |post| %>
  <%= render 'posts/post', post: post %>
<% end %>

app/views/profiles/unfollow.js.erb
$('#unfollow-button').text('Follow').attr('class', 'btn follow-button').attr('href', "/<%= user.user_name %>/follow_user").attr('id', 'follow-button');