config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  resources :posts do
    resources :comments
  end
  root "posts#index"

  get ":user_name", to: "profiles#show", as: :profile
  get ":user_name/edit", to: "profiles#edit", as: :edit_profile
  patch ":user_name/edit", to: "profiles#update", as: :update_profile

  get "notifications/:id/link_through", to: "notifications#link_through", as: :link_through
  get "notifications", to: "notifications#index"
  post ":user_name/follow_user", to: "relationships#follow_user", as: :follow_user
  post ":user_name/unfollow_user", to: "relationships#unfollow_user", as: :unfollow_user
  get "browse", to: "posts#browse", as: :browse_posts
  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  def index
    @comments = @post.comments.order("created_at ASC")

    respond_to do |format|
      format.html { render layout: !request.xhr? }
    end
  end

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      create_notification @post, @comment
      respond_to do |format|
        format.html { redirect_to post_path(@post) }
        format.js
      end
    else
      flash.now[:alert] = "Check the comment form something went horribly wrong."
      redirect_to(post_path(@post))
    end
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    if @comment.user_id == current_user.id
      @comment.destroy
      respond_to do |format|
        format.html { redirect_to(post_path(@post)) }
        format.js
      end
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:content)
    end

    def set_post
      @post = Post.find(params[:post_id])
    end

    def create_notification(post)
      return if post.user.id == current_user.id
      Notification.create(user_id: post.user.id, notified_by_id: current_user.id, post_id: post.id, comment_id: comment.id, notice_type: "comment")
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="user-name">
  <% if comment.user %>
    <%= link_to comment.user.user_name, profile_path(comment.user.user_name) %>
  <% end %>
</div>
<div class="comment-content">
  <%= comment.content %>
  <% if current_user && comment.user == current_user %>
    <%= link_to post_comment_path(post, comment), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this post?", post_id: post.id, value: post.comments.count }, remote: true, id: "delete-#{comment.id}", class: "delete-comment" do %>              
      <i class="bi bi-trash"></i>
    <% end %>
  <% end %>
</div>

app/views/comments/create.js.erb
$('#comments_content_<%= @post.id %>').blur();
$('#comment_content_<%= @post.id %>').val('');
Append.comment_count += 1
$(Append.id).attr('data-value', Append.comment_content);

if (Append.comment || Append.open) {
  $('#comments_<%= @post.id %>').append("<%=j render 'comments/comment', post: @post, comment: @comment %>");
}
else if ((Append.comment && Append.open) === false && Append.link === true) {
  $('#comments_' + Append.post_id).append("<div class='paginator' id='comments-paginator-" + Append.post_id + "'><a class='more-comments id='more_comments_" + Append.post_id + "' data-post_id='" + Append.post_id + "' data-type='html' data-remote='true' data-value='" + Append.comment_count + "' href='/posts/" + Append.post_id + "/comments'>view all " + Append.comment_count + " comments</a></div>");
  ClickableCommentsLink();
}
else if ((Append.comment && Append.open && Append.link) === false) {
  $('#more_comments_<%= @post.id %>').html("view all <%= @post.comment.count %> comments");
}

app/views/comments/destroy.js.erb
$('#comments_<%= @post.id %>').html("<%= j render @post.comments, post: @post, comment: @comments %>");
Append.comment_count -= 1;

app/views/comments/index.html.erb
<%= render @comments, post: @post %>