config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  resources :posts do
    resources :comments
  end
  root "posts#index"

  get ":user_name", to: "profiles#show", as: :profile
  get ":user_name/edit", to: "profiles#edit", as: :edit_profile
  patch ":user_name/edit", to: "profiles#update", as: :update_profile

  get "notifications/:id/link_through", to: "notifications#link_through", as: :link_through
  get "notifications", to: "notifications#index"
  post ":user_name/follow_user", to: "relationships#follow_user", as: :follow_user
  post ":user_name/unfollow_user", to: "relationships#unfollow_user", as: :unfollow_user
  get "browse", to: "posts#browse", as: :browse_posts
  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord
  validates :user_id, presence: true
  validates :content, presence: false
  validates :images, presence: false

  has_many_attached :images, dependent: :destroy
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy

  scope :of_followed_users, ->(following_users) { where user_id: following_users }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [ :show, :edit, :update, :destroy ]
  before_action :authenticate_user!, only: [ :new, :edit, :create, :update, :destroy ]
  before_action :owned_post, only: [ :edit, :update, :destroy ]

  def browse
    @posts = Post.all.order("created_at DESC").page params[:page]
  end
  def index
    @posts = Post.of_followed_users(current_user.following).order("created_at DESC").page params[:page]
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      flash[:success] = "Your post has been created"
      redirect_to posts_path
    else
      flash.now[:alert] = "Your new post couldn't be created! Please check the form"
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:success] = "Post updated."
      redirect_to(post_path(@post))
    else
      flash.now[:alert] = "Update failed. Please check the form."
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private
    def post_params
      params.expect(post: [ :content, images: [] ])
    end

    def set_post
      @post = Post.find(params[:id])
    end

    def owned_post
      unless current_user == @post.user
        flash[:alert] = "That post doesn't belong to you!"
        redirect_to root_path
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="post-body">
      <div class="image-wrap">
        <%= simple_form_for post, html: { class: 'form-horizontal', multipart: true } do |f| %>
          <div class="row">
            <div class="col-md-12 text-center">
              <%= f.error_notification %>
            </div>
          </div>
          <div class="container-fluid">
            <div class="form-group text-center">
              <%= f.input :content %>
            </div>

            <div class="form-group">
              <%= f.input :images %>

            </div>
            <div class="form-group text-center">
              <%= f.button :submit, class: "btn-success btn-block" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/_post.html.erb
<div class="posts-wrapper row">
  <div class="post" style="display: flex; flex-direction: column">
    <div class="post-head">
      <div class="thumb-img"></div>
      <div class="user-name"><%= link_to post.user.user_name, profile_path(post.user.user_name) %></div>
      <div class="time-ago"><%= time_ago_in_words post.created_at %> ago</div>
    </div>
    <div class="post-bottom">
      <%= post.content %>
      <%= link_to 'View post', post_path(post) %> 
        <div class="comment" id="comments_<%= post.id %>">
          <% if post.comments.count != 0 %>
            <%= render post.comments.first(4), post: post  %>
            <% unless post.comments.count <= 4 %>
              <div class="paginator" id="comments-paginator-<%= post.id %>">
                <%= link_to "view all #{post.comments.count} comments", post_comments_path(post), remote: true, class: 'more-comments', id: "more-comments_#{post.id}", data: {post_id: "#{post.id}", type: "html",  value: "#{post.comments.count}"} %>
                

            <% end %>
          <% end %>
        </div>
      <div class="comment-like-form row">
        <div class="like-button col-sm-1">
          <i class="bi bi-heart"></i>
        </div>
        <div class="comment-form col-sm-11">
          <%= form_for([post, post.comments.build], remote: true) do |f| %>
            <%= f.text_field :content, placeholder: 'Add a comment...', id: "comment_content_#{post.id}" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/_post_dashboard.html.erb
<div id="posts">
  <%= render "posts/posts" %>
</div>
<div class="text-center" id="paginator">
  <%= link_to_next_page @posts, 'LOAD MORE', remote: true, id: 'load_more' %>
</div>

app/views/posts/_post_dashboard.js.erb
$('#posts').append("<%= escape_javascript(render 'posts/posts')%>");
$('#paginator').html("<%- escape_javascript(link_to_next_page(@posts, 'LOAD MORE', remote: true, id: 'load_more' ))%>");
if (!$('#load_more').length) {$('#paginator').remove(); }

app/views/posts/_posts.html.erb
<% @posts.each do |post| %>
  <%= render 'posts/post', post: post %>
<% end %>

app/views/posts/browse.html.erb
<%= render 'posts/post_dashboard', post: @posts %>

app/views/posts/edit.html.erb
<div class="form-wrapper">
  <div class="text-center edit-links">
    <%= link_to "Delete Post", post_path(@post), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this post?" }, class: "btn btn-danger"%>
    <%= link_to "Back", post_path(@post), class: "btn btn-primary" %>
  </div>
  <%= render "posts/form", post: @post %>
</div>

app/views/posts/index.html.erb
<%= render 'posts/post_dashboard', posts: @posts %>

app/views/posts/index.js.erb
$('#posts').append("<%= escape_javascript(render 'posts/posts')%>");
$('#paginator').html("<%- escape_javascript(link_to_next_page(@posts, 'LOAD MORE', remote: true, id: 'load_more' ))%>");
if (!$('#load_more').length) {$('#paginator').remove(); }
console.log('test');

app/views/posts/new.html.erb
<div class="form-wrapper">
  <%= render "posts/form", post: @post %>
</div>

app/views/posts/show.html.erb
<%= render 'posts/post', post: @post %>
<div class="text-center edit-links">
  <%= link_to "Cancel", posts_path %>
  <% if current_user && @post.user.id == current_user.id %>
    <%= link_to "Edit Post", edit_post_path(@post) %>
  <% end %>
</div>